# Generated by Django 3.0.6 on 2020-07-12 08:40

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('version', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a sections of articles', max_length=30)),
                ('priority', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a section name', max_length=100)),
                ('language', models.CharField(choices=[('ru', 'russian'), ('en', 'english')], default='en', help_text='check language', max_length=2)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='documentation.Section')),
            ],
            options={
                'verbose_name': 'Section Content',
                'verbose_name_plural': 'Sections Contents',
            },
        ),
        migrations.CreateModel(
            name='ArticlesContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a titles article', max_length=100)),
                ('body', tinymce.models.HTMLField(help_text='Enter a text article')),
                ('language', models.CharField(choices=[('ru', 'russian'), ('en', 'english')], default='en', help_text='check language', max_length=2)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='documentation.Article')),
            ],
            options={
                'verbose_name': 'Articles Content',
                'verbose_name_plural': 'Articles Contents',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.Section'),
        ),
    ]
