# Generated by Django 3.0.6 on 2020-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a titles article', max_length=100)),
                ('body', models.TextField(help_text='Enter a text article')),
            ],
        ),
    ]
