# Generated by Django 3.0.6 on 2020-07-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='articlescontent',
            name='language',
            field=models.CharField(choices=[('ru', 'russian'), ('en', 'english')], default='en', help_text='check language', max_length=2),
        ),
    ]
