# Generated by Django 3.0.6 on 2020-06-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20200617_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
