# Generated by Django 3.0.6 on 2020-07-01 07:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20200618_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(help_text='Enter a text article'),
        ),
    ]
